### PR TITLE
Making the botsheeter/shotter scripts more general

### PR DESCRIPTION
**Pull request by stefanbohacek**
@hugovk 

So, I apologize for the sloppy programming. There's quite a bit of optimization to be done here, but this is still work in progress.

For example, I just realized that I will have to put back in the field into the bot submission form that asks users about the bot's name.

I thought we can just figure it out from the URL, or we can ask for bots that don't have web profiles, like Snapchat bots, but I absolutely forgot about YouTube bots -- and another problem I only realized now is when the bot has a "preferred" capitalization, for example [ThatForestBot](http://thatforestbot.tumblr.com/), whose name from the URL is _thatforestbot_.

This may not seem like a big deal, but if you look at the submitted description:

> ThatForestBot searches for amazing forest pictures to show you the wonders of the world surrounding you.

So it just seems to make sense to let people decide what the actual name should be and work around that. most people will probably just copy/paste the handle.

Hmm, now I'm thinking that we can actually keep the way it's done in case the person submitting the bot uses the URL as bot's name. So something like

```
if 'http' in bot_name:
    bot['username'] = url_to_username(row[999])
else:
    # Remove leading/trailing white space, replace spaces with underscores, etc
    bot['username'] = clean_up(row[999])  
```

You get the idea.

For now, I'll just wait for you to have a quick look at the changes, if you'd like, and merge this, then proceed with the rest of the updates -- and eventually clean things up.

### CODE REVIEW

**Comment by stefanbohacek** [comment]
So I just found an issue when handling multiple bots.

```
Creating thumbnails...
Creating thumbnail from http://thatforestbot.tumblr.com/, saving to ../content/bots/tumblr-bots/images/...
Creating thumbnail from https://twitter.com/moonshotbot, saving to ../content/bots/tumblr-bots/images/...
```

Investigating. Is this just running async and needs a closure (or whatever you call these in Python)?

**Comment by stefanbohacek** [comment]
Alright, should be good now.

**Comment by stefanbohacek** [comment]
Merging this for now, feel free to look at the changes later.

**Comment by hugovk** [comment]
Looks good, I'll submit a PR with some minor refactors.

**Pull request merged**
