### PR TITLE
Added slack-gamebot, made the botsheeter output messages more useful/…

### PR DESCRIPTION
**Pull request by stefanbohacek**
…usable.

### CODE REVIEW

**Comment by stefanbohacek** [comment]
@hugovk Ah, could you help me figure out what I broke?

Also, I can't remember now, did you say you use OSX? I'd like to see if the colored output works for you.

**Comment by stefanbohacek** [comment]
@hugovk Okay, never mind, got it!

My questions on the colored output still stands.

**Comment by hugovk** [comment]
Not on OS X right now, but Windows doesn't show coloured output. Both cmd.exe and Git BASH:

`←[1;31mUnable to make screenshot for slack-gamebot, please do it manually←[1;m`

**Comment by hugovk** [comment]
On OS X, I got this text in green:

`Finished processing, skipped 39 bots:`

I wouldn't worry too much about the Windows output (although [Colorama](https://pypi.python.org/pypi/colorama) is good for this stuff).

**Comment by stefanbohacek** [comment]
Oh, that looks nice! I think I'm just going to add this later, I'd rather the output to look nice everywhere :-)

Thanks for the link!

**Pull request merged**
