### PR TITLE
CI: check links in markdown

### PR DESCRIPTION
**Pull request by hugovk**
We can use [markdown-link-check](https://github.com/tcort/markdown-link-check) to check all of the hyperlinks in markdown to determine if they are alive or dead.

For example: https://travis-ci.org/hugovk/botwiki.org/builds/169704157#L602

I also fixed some broken links it found, and added [EditorConfig](http://editorconfig.org/#download) to help maintain standards.

markdown-link-check takes about 3.5 minutes on the CI, which is probably ok. If you prefer, or if it ever starts timing out the CI (> 10 mins), I could change it to only check the files that have changed between master and the current branch.

### CODE REVIEW

**Comment by hugovk** [comment]
Oh, and that one timed out!

**Comment by stefanbohacek** [comment]
@hugovk This is really awesome, thank you!

Yeah, would you mind updating this so only the updated files get checked for broken URLs?

**Comment by hugovk** [comment]
Yes, I'll get that sorted, might take a little time. 

In the meantime, would you like to cherry-pick just the fixed links commit, or shall I send that in it's own PR?

**Comment by stefanbohacek** [comment]
Yeah, I can do that, some time throughout the day. Thank you!

**Pull request closed without merging**
