### PR TITLE
Fix author link

### PR DESCRIPTION
**Pull request by hugovk**

### CODE REVIEW

**Comment by stefanbohacek** [comment]
Ah, thanks for catching that!

**Comment by hugovk** [comment]
Actually, is it even a bot? 

> For the past three months, I’ve been searching for tweets that begin “I’m not racist, but...”, and the results aren’t pretty. 

http://www.independent.co.uk/voices/comment/yes-youre-racist-the-casual-comments-permeating-twitter-8437127.html

> The way of acting of @YesYou’reRacist is to pick different tweets which say“I am not racist but…” and are offensive. Some of them mention dislike of white people, black people, foreigners in general or people from other ethnicities. It’s curious that he set up a search to find these words exactly and found so many tweets. As he said “I found enough tweets in one day to last me for a week, which is quite disturbing”. He even tries to sort through them and weed out the ones that show irony rather than offensive words.

http://blog.nohatespeechmovement.org/yes-youre-racist-the-online-watchdog-that-points-to-you/

Also the recent retweets have come from HootSuite rather than some bot app's name.

**Comment by stefanbohacek** [comment]
@hugovk Oh crap! What a shame, this was my favorite "bot".

Thanks a lot for pointing that out to me, I really need to learn to read!

**Comment by hugovk** [comment]
Others think it's a bot too:
http://money.cnn.com/2014/08/12/technology/social/twitter-bots/
http://www.ibtimes.co.uk/twitter-announces-it-has-23-million-robot-users-here-are-our-favourites-1460943
https://iapp.org/news/a/about-those-creepy-and-not-so-creepy-bots/

**Comment by stefanbohacek** [comment]
Well I actually reached out to the guy to make sure I got the right author, and asked if he made any other bots. He said:

> No, I've never made a bot.

It's obvious to me now, but I managed to somehow understand it as

> No, just this one, I'm not really a bot kind of guy.

Oh well. Let's all just move on.

**Pull request merged**
