### PR TITLE
Add newly submitted bots

### PR DESCRIPTION
**Pull request by hugovk**
Re: `beet_keeper.md`

For "Where can I see this bot?" the answer was http://exponentialdecay.co.uk/blog/not-quite-perfect-a-lil-automatic-twitter-thingy/ which resulted in `.md`. So I edited the sheet to put it as https://twitter.com/beet_keeper which may not be entirely accurate but it lets the script run. Perhaps that needs renaming.

### CODE REVIEW

**Comment by ross-spencer** [comment]
Hi @hugovk , I'm beet_keeper, is there anything I can do to help with that link? - I'm not clear on what the bug is, but can modify it in WordPress? - or create a tweet and link to that?

**Comment by stefanbohacek** [comment]
Hi @ross-spencer, just let me know if the bot is visible somewhere on Twitter, I will take care of the rest :-)

@hugovk Thank you for the PR!

**Comment by ross-spencer** [comment]
Would this Tweet work okay for you Stefan? -
https://twitter.com/beet_keeper/status/686098955399073793

I suspect I've made it a tough one to demo being entirely avatar based thus
far... :)

No big deal if it doesn't quite fit, my Twitter account will be an okay
link.

**Comment by hugovk** [comment]
@stefan It's a cool bot: its job is to update Ross's own avatar!

@ross-spencer Because it's not a conventional post-something-as-updates-to-Twitter bot, the script hit some edge cases. But no problem! I'll edit it manually and update this PR. What's the name of the bot?

**Comment by ross-spencer** [comment]
No snappy name I'm afraid! - The GitHub is just _binary-numbers_ and so I'm
happy with that as a bot name :)

Thx both! ^^

**Comment by hugovk** [comment]
Thanks, renamed and cleaned up and PR updated: https://github.com/botwiki/botwiki.org/pull/99/commits/b62ac890e5b160fd5787923b59343ce854d4fdb2

**Comment by hugovk** [comment]
@fourtonfish Is this good to merge?

**Comment by stefanbohacek** [comment]
@hugovk Perfect, thank you -- and thank you @ross-spencer as well!

**Pull request merged**
