### PR TITLE
Generated from submissions

### PR DESCRIPTION
**Pull request by hugovk**
I've made a script to process Twitter bots (and only Twitter bots for now) from the submissions form, and create .md files and images.

It doesn't update the spreadsheet, just reads from it for now.

How does this look?

### CODE REVIEW

**Comment by stefanbohacek** [comment]
The script is really amazing! A few notes:
- The folder name/path for Twitter bots is `twitterbots`. This is a bit inconsistent with some other networks, for example we have `redditbots`, but then also `youtube-bots` or `snapchat-bots`. Honestly, I don't really know if we need to be consistent here, for example: https://en.wikipedia.org/wiki/Twitterbot -- this mentions both "Twitterbots" and "Twitter bots" or "twitter bots". I just kind of went with whatever felt "natural" for each network.
- Can you remove leading white space from the tags?
- For Twitterbots (Twitter bots?), can we include @ before the bot's name?

**Comment by stefanbohacek** [comment]
Oh, one more thing, can the script insert `true` into a column titled `Added`? 

This way the script can only run through bots that are not marked as added, but we can keep the data instead of automatically deleting anything. So we'll have a backup, justst in case something goes wrong.

**Comment by stefanbohacek** [comment]
I don't know why it didn't occur to me right away, but maybe we can just show a dropdown, on the submit form, asking the user which network the bot operates on? That would remove a lot of the need for parsing.

**Comment by hugovk** [comment]
Yes to all those. I'll update the PR, and also make another one with the scripts.

A dropdown makes sense. Of course there's always the possibility someone's made a somethingelsebot, but I suppose an "Other" option can deal with that. Can you update the form?

**Comment by hugovk** [comment]
> - Can you remove leading white space from the tags?

Right now tags is just from the column D with no processing. For example:

`art, nature, fiction, inspiration, inspiring, escapismtinyworlds`

Do you want to remove all spaces (eg `tags.replace(" "), ""`), or just after commas (eg `tags.replace(", "), ","`).

The former would also remove spaces from inside tags (eg `fish and chips` -> `fishandchips`).

**Comment by hugovk** [comment]
PR updated.
- [x] Remove leading white space from the tags
  - Removes all spaces, but should we keep spaces in tags?
  - Should we also add the creator name to the tags?
- [x] For Twitterbots, include @ before the bot's name
- [x] insert `true` into a column titled `Added`

I also added the Python scripts in this PR too. Seems simpler that way, as they go hand-in-hand with this generated content.

Private credentials are needed in botsheeter.json, you can make your own by following [this](https://gspread.readthedocs.org/en/latest/oauth2.html) but I can probably share mine privately.

TODO
- [ ] Show a dropdown, on the submit form, asking the user which network the bot operates on

**Comment by stefanbohacek** [comment]
Awesome job!

Hm, it's a bit funny about the spaces _in_ the actual tags. See [this](https://botwiki.org/tag/open%20source) for something really embarassing.

Basically, we need to really [sort out the search/tagging](https://github.com/botwiki/botwiki.org/issues/19), because right now it matches pretty strictly and as a pretty bad short term solution I started doing something like this with tags:

> #opensource #open source #node.js #nodejs #node

Yep.

So I'm going to say let's leave the spaces _in_ the actual tags, because a long term solution is for those to not matter.

Note: I also added the dropdown to the submission form.

**Comment by hugovk** [comment]
OK PR coming up to retain spaces.

PS run like `python other/botsheeter.py -h` from the root of the repo.

**Comment by stefanbohacek** [comment]
:+1:

**Comment by hugovk** [comment]
> Oh, one more thing, can the script insert true into a column titled Added?
> 
> This way the script can only run through bots that are not marked as added, but we can keep the data instead of automatically deleting anything. So we'll have a backup, just in case something goes wrong

Just realised I only set the script to insert true in the column, and doesn't check the value. Right now it only creates a new .md if no .md file already exists, and only takes a new screenshot if no .png already exists.

I'll add the extra check so if a bot is marked as added, it won't be processed. I'll leave the file-exists checks too.

**Comment by stefanbohacek** [comment]
The file existence check is very nice!

**Pull request merged**
